//TODO: convert to array of objects
export const GoogleLanguages = [
    // ['Abkhazian','ab'],
    ['Afar','aa'],
    ['Afrikaans','af'],
    ['Albanian','sq'],
    ['Amharic','am'],
    ['Arabic','ar'],
    ['Aragonese','an'],
    ['Armenian','hy'],
    ['Assamese','as'],
    ['Avestan','ae'],
    ['Aymara','ay'],
    ['Azerbaijani','az'],
    ['Bashkir','ba'],
    ['Basque','eu'],
    ['Belarusian','be'],
    ['Bengali','bn'],
    ['Bihari','bh'],
    ['Bislama','bi'],
    ['Bosnian','bs'],
    ['Breton','br'],
    ['Bulgarian','bg'],
    ['Burmese','my'],
    ['Catalan','ca'],
    ['Chamorro','ch'],
    ['Chechen','ce'],
    ['Chinese','zh'],
    ['Church Slavic/ Slavonic/ Old Bulgarian','cu'],
    ['Chuvash','cv'],
    ['Cornish','kw'],
    ['Corsican','co'],
    ['Croatian','hr'],
    ['Czech','cs'],
    ['Danish','da'],
    ['Divehi/ Dhivehi/ Maldivian','dv'],
    ['Dutch','nl'],
    ['Dzongkha','dz'],
    // ['English','en'],
    ['Esperanto','eo'],
    ['Estonian','et'],
    ['Faroese','fo'],
    ['Fijian','fj'],
    ['Finnish','fi'],
    ['French','fr'],
    ['Gaelic/ Scottish Gaelic','gd'],
    ['Galician','gl'],
    ['Georgian','ka'],
    ['German','de'],
    ["Greek, Modern (1453-)",'el'],
    ['Guarani','gn'],
    ['Gujarati','gu'],
    ['Haitian/ Haitian Creole','ht'],
    ['Hausa','ha'],
    ['Hebrew','he'],
    ['Herero','hz'],
    ['Hindi','hi'],
    ['Hiri Motu','ho'],
    ['Hungarian','hu'],
    ['Icelandic','is'],
    ['Ido','io'],
    ['Indonesian','id'],
    ['Interlingua (International Auxiliary Language Association)','ia'],
    ['Interlingue','ie'],
    ['Inuktitut','iu'],
    ['Inupiaq','ik'],
    ['Irish','ga'],
    ['Italian','it'],
    ['Japanese','ja'],
    ['Javanese','jv'],
    ['Kalaallisut','kl'],
    ['Kannada','kn'],
    ['Kashmiri','ks'],
    ['Kazakh','kk'],
    ['Khmer','km'],
    ['Kikuyu/ Gikuyu','ki'],
    ['Kinyarwanda','rw'],
    ['Kirghiz','ky'],
    ['Komi','kv'],
    ['Korean','ko'],
    ['Kuanyama/ Kwanyama','kj'],
    ['Kurdish','ku'],
    ['Lao','lo'],
    ['Latin','la'],
    ['Latvian','lv'],
    ['Limburgan/ Limburger/ Limburgish','li'],
    ['Lingala','ln'],
    ['Lithuanian','lt'],
    ['Luxembourgish/ Letzeburgesch','lb'],
    ['Macedonian','mk'],
    ['Malagasy','mg'],
    ['Malay','ms'],
    ['Malayalam','ml'],
    ['Maltese','mt'],
    ['Manx','gv'],
    ['Maori','mi'],
    ['Marathi','mr'],
    ['Marshallese','mh'],
    ['Moldavian','mo'],
    ['Mongolian','mn'],
    ['Nauru','na'],
    ["Navaho, Navajo",'nv'],
    ["Ndebele, North",'nd'],
    ["Ndebele, South",'nr'],
    ['Ndonga','ng'],
    ['Nepali','ne'],
    ['Northern Sami','se'],
    ['Norwegian','no'],
    ['Norwegian Bokmal','nb'],
    ['Norwegian Nynorsk','nn'],
    ['Nyanja/ Chichewa/ Chewa','ny'],
    ['Occitan (post 1500)/ Provencal','oc'],
    ['Oriya','or'],
    ['Oromo','om'],
    ['Ossetian/ Ossetic','os'],
    ['Pali','pi'],
    ['Panjabi','pa'],
    ['Persian','fa'],
    ['Polish','pl'],
    ['Portuguese','pt'],
    ['Pushto','ps'],
    ['Quechua','qu'],
    ['Raeto-Romance','rm'],
    ['Romanian','ro'],
    ['Rundi','rn'],
    ['Russian','ru'],
    ['Samoan','sm'],
    ['Sango','sg'],
    ['Sanskrit','sa'],
    ['Sardinian','sc'],
    ['Serbian','sr'],
    ['Shona','sn'],
    ['Sichuan Yi','ii'],
    ['Sindhi','sd'],
    ['Sinhala/ Sinhalese','si'],
    ['Slovak','sk'],
    ['Slovenian','sl'],
    ['Somali','so'],
    ["Sotho, Southern",'st'],
    ['Spanish/ Castilian','es'],
    ['Sundanese','su'],
    ['Swahili','sw'],
    ['Swati','ss'],
    ['Swedish','sv'],
    ['Tagalog','tl'],
    ['Tahitian','ty'],
    ['Tajik','tg'],
    ['Tamil','ta'],
    ['Tatar','tt'],
    ['Telugu','te'],
    ['Thai','th'],
    ['Tibetan','bo'],
    ['Tigrinya','ti'],
    ['Tonga (Tonga Islands)','to'],
    ['Tsonga','ts'],
    ['Tswana','tn'],
    ['Turkish','tr'],
    ['Turkmen','tk'],
    ['Twi','tw'],
    ['Uighur','ug'],
    ['Ukrainian','uk'],
    ['Urdu','ur'],
    ['Uzbek','uz'],
    ['Vietnamese','vi'],
    ['Volapuk','vo'],
    ['Walloon','wa'],
    ['Welsh','cy'],
    ['Western Frisian','fy'],
    ['Wolof','wo'],
    ['Xhosa','xh'],
    ['Yiddish','yi'],
    ['Yoruba','yo'],
    ['Zhuang/ Chuang','za'],
    ['Zulu','zu']

  ];